/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.vrview;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.google.vr.sdk.widgets.video.VrVideoView;

@Kroll.module(name = "Vrview", id = "de.appwerft.vrview")
public class VrviewModule extends KrollModule {
	// Indicates that the video is in a standard video container format such as
	// mp4, webm, ogg, aac.
	final static int FORMAT_DEFAULT = VrVideoView.Options.FORMAT_DEFAULT;
	// Indicates that the video uses the HTTP Live Streaming (HLS) format.
	final static int FORMAT_HLS = VrVideoView.Options.FORMAT_HLS;
	// Each video frame is a monocular equirectangular panorama.
	final static int TYPE_MONO = VrVideoView.Options.TYPE_MONO;
	// Each video frame contains two vertically-stacked equirectangular
	// panoramas.
	final static int TYPE_STEREO_OVER_UNDER = VrVideoView.Options.TYPE_STEREO_OVER_UNDER;

	public VrviewModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		// put module init code that needs to run when the application is
		// created
	}

	// Methods
	@Kroll.method
	public String example() {
		return "hello world";
	}

	// Properties
	@Kroll.getProperty
	public String getExampleProp() {
		return "hello world";
	}

	@Kroll.setProperty
	public void setExampleProp(String value) {
	}

}
