/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.vrview;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;

// This proxy can be created by calling Vrview.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = VrviewModule.class)
public class VrVideoViewProxy extends TiViewProxy {
	// Standard Debugging variables
	private static final String LCAT = "VRview";
	private Boolean isStereo = false;
	private int mediaType = 0;
	private String image = null;
	private String video = null;

	private class ExampleView extends TiUIView {
		public ExampleView(TiViewProxy proxy) {
			super(proxy);
			LayoutArrangement arrangement = LayoutArrangement.DEFAULT;

			if (proxy.hasProperty(TiC.PROPERTY_LAYOUT)) {
				String layoutProperty = TiConvert.toString(proxy
						.getProperty(TiC.PROPERTY_LAYOUT));
				if (layoutProperty.equals(TiC.LAYOUT_HORIZONTAL)) {
					arrangement = LayoutArrangement.HORIZONTAL;
				} else if (layoutProperty.equals(TiC.LAYOUT_VERTICAL)) {
					arrangement = LayoutArrangement.VERTICAL;
				}
			}
			setNativeView(new TiCompositeLayout(proxy.getActivity(),
					arrangement));
		}

		@Override
		public void processProperties(KrollDict d) {
			super.processProperties(d);
		}
	}

	// Constructor
	public VrVideoViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new ExampleView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
		if (options.containsKey("isStereo")) {
			isStereo = options.getBoolean("isStereo");
		}
		if (options.containsKey("image")) {
			image = options.getString("image");
		}
		if (options.containsKey("video")) {
			video = options.getString("video");
		}
	}

	@Kroll.method
	public void loadVideoFromRessourceFolder(String uri, KrollDict opts) {
	}

	@Kroll.method
	public void loadVideo(String uri, KrollDict opts) {
	}

	@Kroll.method
	public void playVideo() {
	}

	@Kroll.method
	public void pauseVideo() {
	}

	@Kroll.getProperty
	@Kroll.method
	public Boolean getIsStereo() {
		return isStereo;
	}

}